apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cyber-exam
  region: eu-west-1

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
    volumeSize: 10
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-2
    instanceType: t3.medium
    desiredCapacity: 1
    volumeSize: 10
    ssh:
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub