apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-hello
spec:
  acme:
    email: cecilio.cannav+102@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-hello
    solvers:
    - http01:
        ingress:
          class: nginx